# Generated by Django 3.2 on 2023-01-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_reviews',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title_id')},
        ),
    ]
